### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by MariasStory** [wyf0912/LLFlow#1]
Hi,
Thank you for the interesting solution.
The light weight model may event be fit for web (tfjs).

Can you please provide a docker file to run the test on own images?

In my simple test with pytorch 1.10.0, I had to install:
```
pip install natsort
pip install cv2
pip install opencv-python-headless
pip install scikit-image
pip install lpips
pip install pandas
```

Still I got an error:
```
Traceback (most recent call last):
  File "test.py", line 185, in <module>
    main()
  File "test.py", line 86, in main
    model, opt = load_model(conf_path)
  File "test.py", line 29, in load_model
    model.load_network(load_path=model_path, network=model.netG)
  File "/data/code/models/base_model.py", line 112, in load_network
    network.load_state_dict(load_net_clean, strict=strict)
  File "/opt/bitnami/python/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for LLFlow:
        Missing key(s) in state_dict: "RRDB.RRDB_trunk.4.RDB1.conv1.weight",...
```
I guess that it is a wrong pytorch version, but don't have time to play with it.

**Comment by wyf0912** [comment]
Thanks for your interest in our work. 
Though I did not test our code with PyTorch 1.1, I think the problem is that you used a wrong config.

I just check the released model and there is no `RRDB.RRDB_trunk.4.` in our light-weight model.
``` python
para_names = [name for name in model.netG.state_dict()]
"RRDB.RRDB_trunk.4.RDB1.conv1.weight" in para_names
False
"RRDB.RRDB_trunk.3.RDB1.conv1.weight" in para_names
True
```

You can modify the file `code\confs\LOL_smallNet.yml` to test on your own images
