### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by gwp2021** [wyf0912/LLFlow#10]
hello,you work is pretty good! But I meet some troubles when i train the model by my own dataset. It is shown like this
`<epoch:  1, iter:     200, lr:4.500e-04, t:1.77e+00, td:1.01e-02, eta:1.46e+01, nll:-1.825e+01> 
Traceback (most recent call last):
  File "train.py", line 345, in <module>
    main()
  File "train.py", line 301, in main
    avg_psnr = avg_psnr / idx
ZeroDivisionError: float division by zero`
As you can see, the training shows incorrect t, td, ETA, and NLL.  I guess maybe idX and NLL can't count correctly, but I don't know how to fix it.  Have you ever encountered this problem?  I really hope you can answer  ！thank you

**Comment by gwp2021** [comment]
> 

Thank you for your reply. It was solved by just changing the format to JPG.  But the results of training with my own data were very poor, the result is  mass of black.  Do you have any suggestions for building my own training data ?

**Comment by gwp2021** [comment]
Thank you for your reply. It was solved by just changing the format to JPG. But the results of training with my own data were very poor, the result is mass of black. Do you have any suggestions for building my own training data ?

**Comment by wyf0912** [comment]
It seems that the *nll* from your log is abnormal. I cannot obtain such a small loss even when finishing the training.

What's the size of your own dataset? It seems like an overfitting problem.
