### ISSUE TITLE
psnr ssim is none

### ISSUE THREAD

**Issue by YLongJin** [wyf0912/LLFlow#11]
I download the code and modify the data path but got the psnr ssim is none

**Comment by wyf0912** [comment]
If you test the image with paired reference, you could try "test.py".

**Comment by wyf0912** [comment]
I think you may need to check if your modified path is compatible with the code.

**Comment by YLongJin** [comment]
I got the PSNR in LOL is 0.21, can not get 0.25

**Comment by wyf0912** [comment]
> I got the PSNR in LOL is 0.21, can not get 0.25

Can you generate normally exposed images?

**Comment by YLongJin** [comment]
I just follow the train which is "python train.py --opt your_config_path".  The normally exposed means the last generate images?  
I can get the last enhancement images, it is strange for me that  psnr is lower than your paper.

**Comment by wyf0912** [comment]
You could refer to this issue

https://github.com/wyf0912/LLFlow/issues/8
