### ISSUE TITLE
训练时候出现NAN的情况

### ISSUE THREAD

**Issue by 1013990424** [wyf0912/LLFlow#14]
22-06-02 16:46:36.522 - INFO: <epoch: 40, iter:   1,740> psnr: 2.2714e+01 SSIM: 7.9226e-01
22-06-02 16:47:51.099 - INFO: # Validation # PSNR: 2.2015e+01 SSIM: 7.8545e-01
22-06-02 16:47:51.099 - INFO: <epoch: 40, iter:   1,760> psnr: 2.2015e+01 SSIM: 7.8545e-01
22-06-02 16:49:08.725 - INFO: # Validation # PSNR: 2.2413e+01 SSIM: 7.8182e-01
22-06-02 16:49:08.726 - INFO: <epoch: 41, iter:   1,780> psnr: 2.2413e+01 SSIM: 7.8182e-01
<epoch: 41, iter:   1,800, lr:1.800e-04, t:3.79e+00, td:4.99e-02, eta:4.03e+01, nll:-1.410e+01> 
22-06-02 16:50:23.710 - INFO: # Validation # PSNR: 2.3476e+01 SSIM: 7.7006e-01
22-06-02 16:50:23.711 - INFO: <epoch: 41, iter:   1,800> psnr: 2.3476e+01 SSIM: 7.7006e-01
22-06-02 16:51:41.445 - INFO: # Validation # PSNR: 2.3458e+01 SSIM: 7.7498e-01
22-06-02 16:51:41.446 - INFO: <epoch: 42, iter:   1,820> psnr: 2.3458e+01 SSIM: 7.7498e-01
22-06-02 16:52:56.995 - INFO: # Validation # PSNR: 2.3248e+01 SSIM: 7.9559e-01
22-06-02 16:52:56.995 - INFO: <epoch: 42, iter:   1,840> psnr: 2.3248e+01 SSIM: 7.9559e-01
22-06-02 16:54:14.513 - INFO: # Validation # PSNR: 2.1923e+01 SSIM: 7.8828e-01
22-06-02 16:54:14.513 - INFO: <epoch: 43, iter:   1,860> psnr: 2.1923e+01 SSIM: 7.8828e-01
22-06-02 16:55:29.155 - INFO: # Validation # PSNR: 2.3526e+01 SSIM: 7.2573e-01
22-06-02 16:55:29.155 - INFO: <epoch: 43, iter:   1,880> psnr: 2.3526e+01 SSIM: 7.2573e-01
<epoch: 44, iter:   1,900, lr:1.900e-04, t:3.83e+00, td:7.98e-02, eta:4.06e+01, nll:-1.437e+01> 
22-06-02 16:56:46.834 - INFO: # Validation # PSNR: 2.3193e+01 SSIM: 7.6726e-01
22-06-02 16:56:46.834 - INFO: <epoch: 44, iter:   1,900> psnr: 2.3193e+01 SSIM: 7.6726e-01
22-06-02 16:58:01.565 - INFO: # Validation # PSNR: 2.1788e+01 SSIM: 7.8349e-01
22-06-02 16:58:01.566 - INFO: <epoch: 44, iter:   1,920> psnr: 2.1788e+01 SSIM: 7.8349e-01
22-06-02 16:59:18.780 - INFO: # Validation # PSNR: 2.3761e+01 SSIM: 7.9732e-01
22-06-02 16:59:18.780 - INFO: <epoch: 45, iter:   1,940> psnr: 2.3761e+01 SSIM: 7.9732e-01
22-06-02 17:00:33.713 - INFO: # Validation # PSNR: 2.3915e+01 SSIM: 7.9458e-01
22-06-02 17:00:33.713 - INFO: <epoch: 45, iter:   1,960> psnr: 2.3915e+01 SSIM: 7.9458e-01
22-06-02 17:01:51.351 - INFO: # Validation # PSNR: 2.3342e+01 SSIM: 7.6980e-01
22-06-02 17:01:51.351 - INFO: <epoch: 46, iter:   1,980> psnr: 2.3342e+01 SSIM: 7.6980e-01
<epoch: 46, iter:   2,000, lr:2.000e-04, t:3.79e+00, td:5.20e-02, eta:4.00e+01, nll:-1.445e+01> 
22-06-02 17:03:06.338 - INFO: # Validation # PSNR: 2.3837e+01 SSIM: 7.9719e-01
22-06-02 17:03:06.338 - INFO: <epoch: 46, iter:   2,000> psnr: 2.3837e+01 SSIM: 7.9719e-01
22-06-02 17:04:20.938 - INFO: # Validation # PSNR: 2.4228e+01 SSIM: 7.9535e-01
22-06-02 17:04:20.938 - INFO: <epoch: 46, iter:   2,020> psnr: 2.4228e+01 SSIM: 7.9535e-01
22-06-02 17:04:20.938 - INFO: Saving best models
22-06-02 17:05:39.073 - INFO: # Validation # PSNR: 2.4125e+01 SSIM: 7.7098e-01
22-06-02 17:05:39.073 - INFO: <epoch: 47, iter:   2,040> psnr: 2.4125e+01 SSIM: 7.7098e-01
22-06-02 17:06:53.739 - INFO: # Validation # PSNR: 2.4366e+01 SSIM: 7.8451e-01
22-06-02 17:06:53.740 - INFO: <epoch: 47, iter:   2,060> psnr: 2.4366e+01 SSIM: 7.8451e-01
22-06-02 17:06:53.740 - INFO: Saving best models
22-06-02 17:08:12.200 - INFO: # Validation # PSNR: 2.3133e+01 SSIM: 8.0574e-01
22-06-02 17:08:12.200 - INFO: <epoch: 48, iter:   2,080> psnr: 2.3133e+01 SSIM: 8.0574e-01
<epoch: 48, iter:   2,100, lr:2.100e-04, t:3.81e+00, td:5.07e-02, eta:4.01e+01, nll:-1.470e+01> 
22-06-02 17:09:27.285 - INFO: # Validation # PSNR: 2.3492e+01 SSIM: 7.8315e-01
22-06-02 17:09:27.285 - INFO: <epoch: 48, iter:   2,100> psnr: 2.3492e+01 SSIM: 7.8315e-01
22-06-02 17:10:45.385 - INFO: # Validation # PSNR: 2.3993e+01 SSIM: 7.7895e-01
22-06-02 17:10:45.385 - INFO: <epoch: 49, iter:   2,120> psnr: 2.3993e+01 SSIM: 7.7895e-01
22-06-02 17:12:00.666 - INFO: # Validation # PSNR: 2.3472e+01 SSIM: 7.9519e-01
22-06-02 17:12:00.666 - INFO: <epoch: 49, iter:   2,140> psnr: 2.3472e+01 SSIM: 7.9519e-01
22-06-02 17:13:17.630 - INFO: # Validation # PSNR: 2.4151e+01 SSIM: 7.9518e-01
22-06-02 17:13:17.630 - INFO: <epoch: 50, iter:   2,160> psnr: 2.4151e+01 SSIM: 7.9518e-01
22-06-02 17:14:32.791 - INFO: # Validation # PSNR: 2.3569e+01 SSIM: 7.8216e-01
22-06-02 17:14:32.791 - INFO: <epoch: 50, iter:   2,180> psnr: 2.3569e+01 SSIM: 7.8216e-01
<epoch: 51, iter:   2,200, lr:2.200e-04, t:3.83e+00, td:7.13e-02, eta:4.02e+01, nll:-1.421e+01> 
22-06-02 17:15:50.171 - INFO: # Validation # PSNR: 2.3831e+01 SSIM: 8.0239e-01
22-06-02 17:15:50.172 - INFO: <epoch: 51, iter:   2,200> psnr: 2.3831e+01 SSIM: 8.0239e-01
22-06-02 17:17:05.023 - INFO: # Validation # PSNR: 2.3857e+01 SSIM: 7.8366e-01
22-06-02 17:17:05.023 - INFO: <epoch: 51, iter:   2,220> psnr: 2.3857e+01 SSIM: 7.8366e-01
22-06-02 17:18:22.693 - INFO: # Validation # PSNR: 2.4156e+01 SSIM: 7.9386e-01
22-06-02 17:18:22.694 - INFO: <epoch: 52, iter:   2,240> psnr: 2.4156e+01 SSIM: 7.9386e-01
22-06-02 17:19:37.641 - INFO: # Validation # PSNR: 2.4247e+01 SSIM: 8.1077e-01
22-06-02 17:19:37.641 - INFO: <epoch: 52, iter:   2,260> psnr: 2.4247e+01 SSIM: 8.1077e-01
22-06-02 17:20:55.194 - INFO: # Validation # PSNR: 2.4300e+01 SSIM: 7.9351e-01
22-06-02 17:20:55.194 - INFO: <epoch: 53, iter:   2,280> psnr: 2.4300e+01 SSIM: 7.9351e-01
<epoch: 53, iter:   2,300, lr:2.300e-04, t:3.80e+00, td:5.24e-02, eta:3.98e+01, nll:-1.458e+01> 
22-06-02 17:22:10.256 - INFO: # Validation # PSNR: 2.3832e+01 SSIM: 7.3875e-01
22-06-02 17:22:10.256 - INFO: <epoch: 53, iter:   2,300> psnr: 2.3832e+01 SSIM: 7.3875e-01
22-06-02 17:23:25.127 - INFO: # Validation # PSNR: 2.4496e+01 SSIM: 8.0288e-01
22-06-02 17:23:25.128 - INFO: <epoch: 53, iter:   2,320> psnr: 2.4496e+01 SSIM: 8.0288e-01
22-06-02 17:23:25.128 - INFO: Saving best models
22-06-02 17:24:44.229 - INFO: # Validation # PSNR: 2.2438e+01 SSIM: 7.8931e-01
22-06-02 17:24:44.229 - INFO: <epoch: 54, iter:   2,340> psnr: 2.2438e+01 SSIM: 7.8931e-01
22-06-02 17:26:00.054 - INFO: # Validation # PSNR: 2.4096e+01 SSIM: 8.0219e-01
22-06-02 17:26:00.054 - INFO: <epoch: 54, iter:   2,360> psnr: 2.4096e+01 SSIM: 8.0219e-01
22-06-02 17:27:17.756 - INFO: # Validation # PSNR: 2.4343e+01 SSIM: 7.8690e-01
22-06-02 17:27:17.756 - INFO: <epoch: 55, iter:   2,380> psnr: 2.4343e+01 SSIM: 7.8690e-01
<epoch: 55, iter:   2,400, lr:2.400e-04, t:3.82e+00, td:5.53e-02, eta:3.99e+01, nll:-1.636e+01> 
22-06-02 17:28:32.438 - INFO: # Validation # PSNR: 2.4344e+01 SSIM: 7.7306e-01
22-06-02 17:28:32.439 - INFO: <epoch: 55, iter:   2,400> psnr: 2.4344e+01 SSIM: 7.7306e-01
22-06-02 17:29:49.812 - INFO: # Validation # PSNR: 2.4630e+01 SSIM: 7.8660e-01
22-06-02 17:29:49.812 - INFO: <epoch: 56, iter:   2,420> psnr: 2.4630e+01 SSIM: 7.8660e-01
22-06-02 17:29:49.812 - INFO: Saving best models
22-06-02 17:31:05.616 - INFO: # Validation # PSNR: 2.4031e+01 SSIM: 7.9935e-01
22-06-02 17:31:05.616 - INFO: <epoch: 56, iter:   2,440> psnr: 2.4031e+01 SSIM: 7.9935e-01
22-06-02 17:32:22.724 - INFO: # Validation # PSNR: 2.4581e+01 SSIM: 8.0658e-01
22-06-02 17:32:22.724 - INFO: <epoch: 57, iter:   2,460> psnr: 2.4581e+01 SSIM: 8.0658e-01
22-06-02 17:33:37.579 - INFO: # Validation # PSNR: 2.4193e+01 SSIM: 7.9596e-01
22-06-02 17:33:37.579 - INFO: <epoch: 57, iter:   2,480> psnr: 2.4193e+01 SSIM: 7.9596e-01
<epoch: 58, iter:   2,500, lr:2.500e-04, t:3.82e+00, td:7.41e-02, eta:3.98e+01, nll:-1.464e+01> 
22-06-02 17:34:55.110 - INFO: # Validation # PSNR: 2.3714e+01 SSIM: 8.0299e-01
22-06-02 17:34:55.110 - INFO: <epoch: 58, iter:   2,500> psnr: 2.3714e+01 SSIM: 8.0299e-01
22-06-02 17:36:10.035 - INFO: # Validation # PSNR: 2.4123e+01 SSIM: 7.9859e-01
22-06-02 17:36:10.035 - INFO: <epoch: 58, iter:   2,520> psnr: 2.4123e+01 SSIM: 7.9859e-01
22-06-02 17:37:27.051 - INFO: # Validation # PSNR: 2.3793e+01 SSIM: 7.8510e-01
22-06-02 17:37:27.051 - INFO: <epoch: 59, iter:   2,540> psnr: 2.3793e+01 SSIM: 7.8510e-01
22-06-02 17:38:41.986 - INFO: # Validation # PSNR: 2.3959e+01 SSIM: 7.8839e-01
22-06-02 17:38:41.986 - INFO: <epoch: 59, iter:   2,560> psnr: 2.3959e+01 SSIM: 7.8839e-01
22-06-02 17:39:56.507 - INFO: # Validation # PSNR: 2.4116e+01 SSIM: 8.1688e-01
22-06-02 17:39:56.507 - INFO: <epoch: 59, iter:   2,580> psnr: 2.4116e+01 SSIM: 8.1688e-01
<epoch: 60, iter:   2,600, lr:2.600e-04, t:3.79e+00, td:5.16e-02, eta:3.94e+01, nll:-1.540e+01> 
22-06-02 17:41:13.992 - INFO: # Validation # PSNR: 2.4500e+01 SSIM: 8.1474e-01
22-06-02 17:41:13.993 - INFO: <epoch: 60, iter:   2,600> psnr: 2.4500e+01 SSIM: 8.1474e-01
22-06-02 17:42:28.953 - INFO: # Validation # PSNR: 2.3704e+01 SSIM: 7.6469e-01
22-06-02 17:42:28.953 - INFO: <epoch: 60, iter:   2,620> psnr: 2.3704e+01 SSIM: 7.6469e-01
22-06-02 17:43:44.738 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:43:44.738 - INFO: <epoch: 61, iter:   2,640> psnr: nan SSIM: nan
22-06-02 17:44:57.484 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:44:57.485 - INFO: <epoch: 61, iter:   2,660> psnr: nan SSIM: nan
22-06-02 17:46:12.377 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:46:12.378 - INFO: <epoch: 62, iter:   2,680> psnr: nan SSIM: nan
<epoch: 62, iter:   2,700, lr:2.700e-04, t:3.71e+00, td:5.06e-02, eta:3.84e+01, nll:nan> 
22-06-02 17:47:23.281 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:47:23.281 - INFO: <epoch: 62, iter:   2,700> psnr: nan SSIM: nan
22-06-02 17:48:36.760 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:48:36.760 - INFO: <epoch: 63, iter:   2,720> psnr: nan SSIM: nan
22-06-02 17:49:47.502 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:49:47.502 - INFO: <epoch: 63, iter:   2,740> psnr: nan SSIM: nan
22-06-02 17:51:00.415 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:51:00.416 - INFO: <epoch: 64, iter:   2,760> psnr: nan SSIM: nan
22-06-02 17:52:11.508 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:52:11.508 - INFO: <epoch: 64, iter:   2,780> psnr: nan SSIM: nan
<epoch: 65, iter:   2,800, lr:2.800e-04, t:3.62e+00, td:7.12e-02, eta:3.74e+01, nll:nan> 
22-06-02 17:53:24.952 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:53:24.952 - INFO: <epoch: 65, iter:   2,800> psnr: nan SSIM: nan
22-06-02 17:54:36.266 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:54:36.266 - INFO: <epoch: 65, iter:   2,820> psnr: nan SSIM: nan
22-06-02 17:55:49.798 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:55:49.799 - INFO: <epoch: 66, iter:   2,840> psnr: nan SSIM: nan
22-06-02 17:57:00.782 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:57:00.782 - INFO: <epoch: 66, iter:   2,860> psnr: nan SSIM: nan
22-06-02 17:58:11.699 - INFO: # Validation # PSNR: nan SSIM: nan
22-06-02 17:58:11.700 - INFO: <epoch: 66, iter:   2,880> psnr: nan SSIM: nan
<epoch: 67, iter:   2,900, lr:2.900e-04, t:3.60e+00, td:4.90e-02, eta:3.71e+01, nll:nan> 

把warmup_iter设置为5000仍会出现这样的情况，请问需要怎么解决呢？谢谢

**Comment by wyf0912** [comment]
请问你用的是什么数据集 LOL-v2吗？

**Comment by 1013990424** [comment]
> 请问你用的是什么数据集 LOL-v2吗？

是的

**Comment by wyf0912** [comment]
我只小概率遇到过这个问题 通常重新运行程序就可以了 （可以删除掉出问题的checkpoint后恢复训练

此外，可以减小evaluation的频率来加快训练 （“val_freq”可以设置成类似500/1000）

**Comment by wyf0912** [comment]
或许你可以尝试在reference image上添加一个[-0.5, 0.5]均匀分布的噪声 （假设图像reference的值在0-255范围内）

**Comment by wyf0912** [comment]
> 或许你可以尝试在reference image上添加一个[-0.5, 0.5]均匀分布的噪声 （假设图像reference的值在0-255范围内）

可以参照这个issue https://github.com/andreas128/SRFlow/issues/2#issuecomment-711125583

**Comment by Plwy** [comment]
我的训练阶段没有出现问题，但是在推理阶段，有部分图像的输出结果中出现了inf，也导致了ssim计算为nan
