### ISSUE TITLE
How to use only Invertible Neural Networks？

### ISSUE THREAD

**Issue by kaixindeyuesefen** [wyf0912/LLFlow#18]
How to use only Invertible Neural Networks？

**Comment by wyf0912** [comment]
Do you mean in the evaluation phase? or the training phase?

**Comment by kaixindeyuesefen** [comment]
training.

**Comment by wyf0912** [comment]
You could "Glow: Generative Flow with Invertible 1x1 Convolutions"

**Comment by kaixindeyuesefen** [comment]
Thank you very much!

**Comment by wyf0912** [comment]
I originally want to use that encoder for the ablation study. However, I find it's pretty difficult to get converged. So in Table 5 in the paper, I do not report the results that only using the invertible network

**Comment by kaixindeyuesefen** [comment]
Hello, I recently encountered a little problem when reproducing “Glow” for low-light enhancement. I would like to ask if you still have this part of the code, can you provide it?
