### ISSUE TITLE
Questions about the paper

### ISSUE THREAD

**Issue by ph0316** [wyf0912/LLFlow#21]
Hello, I'd like to ask you two questions. The first: why should the input low light image be enhanced by histogram first? Can the low light image be directly sent to the network? Second: you said that you can learn one-to-many using normalizing flow. Where is it?

**Comment by wyf0912** [comment]
1. Our model can directly use raw low-light images as input. Proper hand-crafted features as input will further benefit the robustness. 

2. You can manually modify the input $z$ in the code to get different $x_h$

**Comment by ph0316** [comment]
![image](https://user-images.githubusercontent.com/56188513/175882374-e862affc-d500-49e6-9f36-0ffb8645a894.png)
I can't train when I'm using ’NoEncoder‘?Why is that?

**Comment by wyf0912** [comment]
That encoder is just for ablation and is out of maintenance.

Maybe you could try to modify the following code from 
```
elif opt['cond_encoder'] ==  'NoEncoder':
    self.RRDB = None # NoEncoder(in_nc, out_nc, nf, nb, gc, scale, opt)
```
to
```
elif opt['cond_encoder'] ==  'NoEncoder':
    self.RRDB = NoEncoder(in_nc, out_nc, nf, nb, gc, scale, opt)
```

**Comment by wyf0912** [comment]
I am not sure whether this works. 
If you want to try "NoEncoder", the easiest way is to make the current encoder just output 0.
 
> That encoder is just for ablation and is out of maintenance.
> 
> Maybe you could try to modify the following code from
> 
> ```
> elif opt['cond_encoder'] ==  'NoEncoder':
>     self.RRDB = None # NoEncoder(in_nc, out_nc, nf, nb, gc, scale, opt)
> ```
> 
> to
> 
> ```
> elif opt['cond_encoder'] ==  'NoEncoder':
>     self.RRDB = NoEncoder(in_nc, out_nc, nf, nb, gc, scale, opt)
> ```

**Comment by ph0316** [comment]
I have tried to do this, but the picture is black.

**Comment by wyf0912** [comment]
You could refer to this issue #18 .
It's very difficult to only train the invertible network without conditional features.

**Comment by ph0316** [comment]
Thank you very much！
