### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by wolfworld6** [wyf0912/LLFlow#3]
hello，where is the requirements.txt？could you provide it？

**Comment by wyf0912** [comment]
It is in ./code folder. Sorry for mistake

**Comment by wolfworld6** [comment]
> It is in ./code folder. Sorry for mistake

ths very much！

**Comment by wolfworld6** [comment]
> It is in ./code folder. Sorry for mistake

sorry to bother you ,when I run the code(LOL-pc.yml), I got this error ,RuntimeError: torch.cat(): Sizes of tensors must match except in dimension 1. Got 294 and 293 in dimension 2 (The offending index is 1),I have solved it ,but then I got the other ques, AssertionError: (294, 440, 8),why?

**Comment by wyf0912** [comment]
Are you trying your own dataset? 
Maybe you could pad the image first and then clip the border of the result for the size mismatch problem.

**Comment by wolfworld6** [comment]
> Are you trying your own dataset? Maybe you could pad the image first and then clip the border of the result for the size mismatch problem.

I used LOL-data , https://[drive.google.com](https://drive.google.com/open?id=1OvHuzPBZRBMDWV5AKI-TtIxPCYY8EW70)/open?id=1OvHuzPBZRBMDWV5AKI-TtIxPCYY8EW70,I will check ,thx!

**Comment by wyf0912** [comment]
You could reopen the issue if you have any questions~

**Comment by wyf0912** [comment]
You could refer to the latest version of the code ```test_unpaired.py``` for auto padding and crop.
