### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by testerrth** [wyf0912/LLFlow#30]
Hello, first of all thank you for your contributions in this area, you have done an excellent work.
I am kind of a new to image enhancement and deep learning areas so I want to ask where can we find checkpoints and especially the model path for testing. 
Looking forward to your answer!

**Comment by testerrth** [comment]
> 

I solved the problem by training the model and use results as model path for now but if pre-trained models available anywhere I'd be happy to learn that.

**Comment by wyf0912** [comment]
Glad to hear that~
