### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by wangchx67** [wyf0912/LLFlow#35]
Hi, I found that you used the VE-LOL dataset, however, the visual results of VE-LOL in Figure 7 seem to be the LOLv2 dataset. 

If you train in LOLv1 and apply Cross-Dataset Evaluation in LOLv2, I think it may not very appropriate, since training images of LOLv1 contain part of testing images of LOLv2. 

Another question. I have not found the downloading link of VE-LOL in your cited paper, can you provide an address?

**Comment by wangchx67** [comment]
The present image in Figure 7 is very similar to LOLv2\Real_captured\Test\Normal\00773.png

**Comment by wangchx67** [comment]
I have found the link of VE-LOL on your project page.

**Comment by wyf0912** [comment]
Hi, I also noticed that there are some similar scenes, even in the LOL dataset itself.

We use the same and official split for all methods so it can still represent the performance of models.
