### ISSUE TITLE
It is mentioned in the paper that the detailed structure diagram of the encoder is in the appendix, but I did not find the appendix. Could you please give me a link to the appendix?

### ISSUE THREAD

**Issue by Smile-QT** [wyf0912/LLFlow#37]
It is mentioned in the paper that the detailed structure diagram of the encoder is in the appendix, but I did not find the appendix. Could you please give me a link to the appendix?

**Comment by wyf0912** [comment]
https://wyf0912.github.io/LLFlow/1489%20Low-Light%20Image%20Enhancement%20with%20Normalizing%20Flow_supply_compressed.pdf

**Comment by Smile-QT** [comment]
Thank you so much
