### ISSUE TITLE
About formula (8) in paper

### ISSUE THREAD

**Issue by YangGangZhiQi** [wyf0912/LLFlow#4]
Hi, thanks for your great works.  After reading the paper, I cannot figure out the meaning of  'x' in formula (8).  And how to understand the PDF function fz， which not use variable z in formula (8)?  I would appreciate it if someone could help me.
 
![公式8](https://user-images.githubusercontent.com/87355944/155286435-baf30c9f-00e9-4645-8869-855febf9990d.png)

**Comment by wyf0912** [comment]
Sorry for the typo. It should be $z$.

I forget to re-upload the new version of the arxiv paper.

**Comment by wyf0912** [comment]
You could reopen the issue if you have any questions~
