### ISSUE TITLE
Dear author, thank you for taking the time to read this message. I am very interested in your masterpiece and have read it carefully, but when I read the code, I am not very clear about the structure of "Flow step". Can you provide me with a detailed structure diagram of "Flow step"? Many thanks! My email address: 1309766271@qq.com

### ISSUE THREAD

**Issue by Smile-QT** [wyf0912/LLFlow#40]
Dear author, thank you for taking the time to read this message. I am very interested in your masterpiece and have read it carefully (Low-Light Image Enhancement with Normalizing Flow.), but when I read the code, I am not very clear about the structure of "Flow step". Can you provide me with a detailed structure diagram of "Flow step"? Many thanks! My email address: 1309766271@qq.com

**Comment by wyf0912** [comment]
I guess I have replied by email
