### ISSUE TITLE
TypeError: Could not convert

### ISSUE THREAD

**Issue by Jingut** [wyf0912/LLFlow#43]
I ran test.py and it  didn't work well.
How can I solve this problem?
![캡처](https://github.com/wyf0912/LLFlow/assets/58259999/1eac9406-e164-48b3-a9f8-9b7fccadb66c)

**Comment by wyf0912** [comment]
This problem seems to be related to the interpretation of the path, e.g., some special characters and spaces.

I guess the OS you use is Windows.  You may try to use a relative path instead of an abs path, or try to follow the path definition specification in Windows.
