### ISSUE TITLE
Over compensated brightness

### ISSUE THREAD

**Issue by spacerunner8** [wyf0912/LLFlow#5]
Hello, first of all, great work!

I was testing the model and I found that some output images look very weird. (see below)

I am using the LOLv2.pth model

**Before**
![wedding1](https://user-images.githubusercontent.com/88363430/158760057-09ca51c2-cef0-4b0a-b7f3-62a6a569bab1.jpeg)

**After**
![res](https://user-images.githubusercontent.com/88363430/158759985-5daa8af7-291c-4ddb-8006-fe3cc75782d0.jpeg)

=====
This image work on LOLv2.pth model however it doesn't work on LOL.pth (as below)
**Before**
![daniel](https://user-images.githubusercontent.com/88363430/158760538-a3a7a86d-2fad-4399-b5cb-f55f52b055ec.jpeg)

**After**
![res](https://user-images.githubusercontent.com/88363430/158760518-a6a47fa9-2da2-47fc-9f4d-5e646eabd19f.jpeg)

Any idea how to resolve this?

Thank you

**Comment by spacerunner8** [comment]
FYI this is the result from LOLv2.pth
![res](https://user-images.githubusercontent.com/88363430/158761573-b5e0a601-fe14-4f58-b0af-066e8f0fbaee.jpeg)

**Comment by wyf0912** [comment]
Hi, thanks for your interest in our work.

Our model focuses more on low light image enhancement. It seems that the provided samples are quite different from the training data which are usually uniform dark, e.g., LOL real captured datasets.

Maybe you can try to fine-tune the model using some extra data with similar samples.

**Comment by spacerunner8** [comment]
got it thanks!
