### ISSUE TITLE
关于测试集

### ISSUE THREAD

**Issue by flashszn** [wyf0912/LLFlow#51]
作者你好，我注意到LOL数据集，您在每个epoch都使用了eval15进行测试，那这样eval15即是验证集也是测试集对吗？我是第一次接触low-level vision的任务，如有错误还请斧正

**Comment by wyf0912** [comment]
是的 这个数据集包含485train 15test/eval。没有单独的evaluation set

**Comment by flashszn** [comment]
> 是的 这个数据集包含485train 15test/eval。没有单独的evaluation set

非常感谢您的回复。
