### ISSUE TITLE
关于LOL的数据集的PSNR

### ISSUE THREAD

**Issue by flashszn** [wyf0912/LLFlow#52]
作者您好，请问LOL数据集的PSNR是在RGB空间上进行测试吗? 因为我注意到一些方法是在ycbcr空间的y通道或者转换成灰度图测试的。

**Comment by wyf0912** [comment]
PSNR是在RGB space上测试的 (但是因为gt随机性的存在 仿照kind/kind++通过一个标量对齐了亮度)
如果在y通道或者gray-scale可能结果会偏高

**Comment by flashszn** [comment]
> PSNR是在RGB space上测试的 (但是因为gt随机性的存在 仿照kind/kind++通过一个标量对齐了亮度) 如果在y通道或者gray-scale可能结果会偏高

非常感谢！
