### ISSUE TITLE
Strange noise

### ISSUE THREAD

**Issue by weizh588** [wyf0912/LLFlow#6]
Thanks for your work, but why is there a strange noise in the processed image?
Before:
![image](https://user-images.githubusercontent.com/43931281/160282065-55017082-0b98-4804-8e19-4694dedca4a2.png)

After:
![image](https://user-images.githubusercontent.com/43931281/160281973-04fd266e-c66e-4b47-82c2-ca52f9724264.png)

**Comment by wyf0912** [comment]
It seems that the strange color block is in the raw input image.
I multiple the input image with a constant 12 and here is the result

This kind of "color block" is quite different from the traditional noise in low-light images. It may come from the JPEG compression. You can try the low light in a lossless format.

![untitled](https://user-images.githubusercontent.com/26561397/160283223-74135617-2a90-464e-9bec-3d3c85716416.jpg)
