### ISSUE TITLE
Inference is too slow

### ISSUE THREAD

**Issue by weizh588** [wyf0912/LLFlow#7]
My computing platform is A100, using your Smallnet.pth, but the network inference time is 13s?

**Comment by wyf0912** [comment]
Sorry, the test codes are on the CPU by mistake. I will update the test code late today.

**Comment by wyf0912** [comment]
I just update the test code and you can try now.

**Comment by WEIZHIHONG720** [comment]
Wow！It works ！ Thank you .



发自我的iPhone


------------------ Original ------------------
From: Yufei Wang ***@***.***&gt;
Date: Sun,Mar 27,2022 11:07 PM
To: wyf0912/LLFlow ***@***.***&gt;
Cc: weizh588 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [wyf0912/LLFlow] Inference is too slow (Issue #7)





 
I just update the test code and you can try now.
