### ISSUE TITLE
finetune the overall brightness

### ISSUE THREAD

**Issue by CongHuang96** [wyf0912/LLFlow#8]
Hi，in code/test.py line 148, you use the mean_gt to fine-tune the overall brightness. 

Is it fair to compare with other methods? MIRNet does not fine-tune the brightness.

**Comment by wyf0912** [comment]
We follow the test paradigm of Kind and Kind++ which use mean_gt to fine-tune the overall brightness.

For other competitors which may be greatly affected by the overall brightness, e.g., Zero-DCE, we also fine-tune their overall brightness and report their better results for fair comparison.
